name: Deploy to server test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: build-apps
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          cd $HOME/Projek/geraipi_test
          source $HOME/virtualenv/Projek/geraipi_test/3.10/bin/activate
          git pull origin main
          touch tmp/restart.txt
